[package]
name = "deproject"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
realsense-rust = "1.1.0"
glow = "0.11.2"
glutin = "0.28"
